version: "3.9"

services:
  db:
    image: postgres:13.2
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    build: ./src
    container_name: api
    restart: always
    ports:
      - "8002:8000"
    depends_on:
      - db
    volumes:
      - ./src/:/usr/src/app/
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql://user:password@db/database

volumes:
  postgres_data:

networks:
  default:
      name: fastapi_postgres
